### ISSUE TITLE
[1.16.5-Forge] Mark mod as client side only, makes server "incompatible" in server list.

### ISSUE THREAD

**Issue by Gbergz** [paperfour/SmoothFocus#4]
Title ^

If mod is missing on server it makes the server ping "Incompatible FML Modded Server".
If possible, mark mod as client only.

![image](https://user-images.githubusercontent.com/26634554/119142325-a8f46c80-ba46-11eb-947f-4f96413ce50c.png)

Also, Mod Crashes if loaded on Servers.
Edit: Crash-report. https://gist.github.com/Gbergz/21a96d771e6e80db15406ff27b065929

Thanks,
**-** Gbergz

**Comment by paperfour** [comment]
I've released a beta for the project that should fix this problem. If you could give it a try to see if it worked, that would be greatly appreciated.

**Comment by Gbergz** [comment]
It's confirmed fixed in the newest Beta update. Thanks for the quick fix! :) 👍

**Comment by Gbergz** [comment]
Though, it still crashes on servers. No biggie since its not needed there + it doesn't cause the "Incompatible FML Modded Server" message anymore.

**Comment by paperfour** [comment]
Great!
